import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

export default defineConfig([
    ...nextVitals,
    ...nextTs,
    globalIgnores([
        // eslint-config-next's defaults, restated because globalIgnores replaces them.
        '.next/**',
        'out/**',
        'build/**',
        'next-env.d.ts',
        // Generated by scripts/build-stats.mjs from lib/*.js, which is linted instead.
        'public/stats.js',
        // Playwright output.
        'playwright-report/**',
        'test-results/**',
    ]),
]);
